# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c170b45d8b9f3f07703edf55728c8aadb3f2c0a38f2b93d1b901c8754a4a7aa55c701c97b76882d1377da3c8723a5d4cd40b334f43d5aaaeeaa95d430da98030

test:
  secret_key_base: 05d1251d6316eb99678a4348fcfd446353c24a0f4a1c0b2ebe9719826fed3a41d96afead1bef61e021f6b27a1a2eff052a736a7b3de2b469535023286cbac728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
